title: 'Felix Vogl'
description: 'Welcome to my Portfolio! I am a Student of Business Information Systems at Universität Leipzig
  and I like to word with data! Here are some projects of mine.'
logo: ./images/profile-picture-dummy.png
theme: jekyll-theme-minimal
