title: 'Felix Vogl'
description: 'Welcome to my Portfolio! I am a Student of Business Information Systems at Universität Leipzig
  and I like to work with data! Here are some of my projects.'
logo: ./images/profile-picture-dummy.png
theme: jekyll-theme-minimal
